"""migration for user.

Revision ID: f815216c423e
Revises: 0dacac20da93
Create Date: 2025-10-22 18:32:27.004803

"""

# revision identifiers, used by Alembic.
revision = "f815216c423e"
down_revision = "0dacac20da93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
